:Author: TONMOYKHANAL
:Email: tonmoykhanal86@gmail.com
:Date: 10/08/2018
:Revision: version#
:License: Public Domain

= Project: Hand Guesture Controlled Robot
The ability to control things by a hand seen in movies was like magic, I was so excited to know how it works and try it in real life. So I come out with a very nice project which is a car that can be controlled by moving your hand in the direction you want and the car will follow! it's a cool project and very simple!

== Step 1: Installation

1. Open this file
2. Edit as you like
3. Release to the World!

== Step 2: Assemble the circuit

Assemble the circuit following the diagram layout.png in the Repository.

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 sketch123                => Arduino sketch folder
  ├── sketch123.ino       => main Arduino file
  ├── schematics.png      => (optional) an image of the required schematics
  ├── layout.png          => (optional) an image of the layout
  └── ReadMe.adoc         => this file
....

=== License
This project is released under a {License} License.

=== Contributing
To contribute to this project please contact TONMOYKHANAL <tonmoykhanal86@gmail.com> or www.tonmoykhanal.tech

=== Components 

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10       
| L1 | Red LED        | 2345-asdf   | 5        
| A1 | Arduino Zero   | ABX00066    | 1        
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
